import { IIdea } from "@/types";
import { BusinessModel, Stage } from "@/types";

export const MOCK_IDEAS: IIdea[] = [
  {
    _id: "65f8ae4c2e5df1e0bd8b3a51",
    title: "Personalized Nutrition AI Coach",
    description: "An AI-powered nutrition coach that creates personalized meal plans based on health goals, dietary restrictions, and lifestyle factors.",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-02"),
    isPublic: true,
    userId: "67d78d872e2ed2dc35e42b23",
    userBuyMeACoffeeUrl: "https://buymeacoffee.com/nutritionai",
    industry: ["healthcare", "artificialIntelligence", "foodBeverage"],
    tags: ["nutrition", "ai", "health", "personalization", "wellness"],
    upVotes: 87,
    downVotes: 12,
    problemStatement: "People struggle to find nutrition advice that fits their unique needs, goals, and preferences.",
    relatedUrls: ["https://example.com/nutrition-research", "https://example.com/ai-personalization"],
    stage: "prototype",
    risks: ["AI accuracy limitations", "Regulatory compliance in health advice", "User adoption barriers"],
    businessModel: BusinessModel.freemium,
    uniqueValue: "Personalized meal plans tailored to individual health goals and preferences.",
  },
  {
    _id: "65f8ae4c2e5df1e0bd8b3a52",
    title: "Zero-Waste Grocery Delivery Platform",
    description: "A grocery delivery service that uses reusable containers and packaging, creating a closed-loop system to eliminate waste.",
    createdAt: new Date("2024-01-28"),
    updatedAt: new Date("2024-02-15"),
    isPublic: true,
    userId: "67d78d872e2ed2dc35e42b23",
    userBuyMeACoffeeUrl: "https://buymeacoffee.com/zerowaste",
    industry: ["foodBeverage", "retail", "environmental"],
    tags: ["sustainability", "zero-waste", "grocery", "delivery", "eco-friendly"],
    upVotes: 63,
    downVotes: 8,
    problemStatement: "Traditional grocery delivery services generate significant packaging waste with each order.",
    relatedUrls: ["https://example.com/zero-waste-movement", "https://example.com/sustainable-packaging"],
    stage: "validation",
    risks: ["Operational logistics", "Container return rate", "Cost competitiveness"],
    businessModel: BusinessModel.subscription,
    uniqueValue: "Zero-waste grocery delivery service with reusable containers and packaging.",
  },
  {
    _id: "65f8ae4c2e5df1e0bd8b3a53",
    title: "Peer-to-Peer Skills Exchange Platform",
    description: "A platform where people can exchange skills and knowledge directly, without monetary transactions.",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-03-01"),
    isPublic: true,
    userId: "67d78d872e2ed2dc35e42b23",
    userBuyMeACoffeeUrl: "https://buymeacoffee.com/skillshare",
    industry: ["education", "technology"],
    tags: ["skills", "learning", "community", "peer-to-peer", "knowledge sharing"],
    upVotes: 112,
    downVotes: 15,
    problemStatement: "Education and skill development are often limited by financial barriers and lack of access.",
    relatedUrls: ["https://example.com/p2p-learning", "https://example.com/skill-economy"],
    stage: "mvp",
    risks: ["Community management", "Quality control", "Platform abuse"],
    businessModel: BusinessModel.freemium,
    uniqueValue: "Direct skill exchange platform without monetary transactions.",
  },
  {
    _id: "65f8ae4c2e5df1e0bd8b3a54",
    title: "Smart Home Energy Optimization System",
    description: "An IoT system that optimizes home energy usage by learning patterns and automatically adjusting devices for maximum efficiency.",
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-03-05"),
    isPublic: true,
    userId: "67d78d872e2ed2dc35e42b23",
    userBuyMeACoffeeUrl: "https://buymeacoffee.com/smartenergy",
    industry: ["energy", "technology", "artificialIntelligence"],
    tags: ["smart home", "energy efficiency", "iot", "sustainability", "automation"],
    upVotes: 95,
    downVotes: 11,
    problemStatement: "Homeowners waste energy and money due to inefficient management of home appliances and systems.",
    relatedUrls: ["https://example.com/smart-home-research", "https://example.com/energy-efficiency"],
    stage: "prototype",
    risks: ["Device compatibility", "Privacy concerns", "Installation complexity"],
    businessModel: BusinessModel.hardwarePlusSoftware,
    uniqueValue: "Smart home energy optimization system that learns patterns and adjusts devices for maximum efficiency.",
  },
  {
    _id: "65f8ae4c2e5df1e0bd8b3a55",
    title: "Crowdsourced Urban Planning Platform",
    description: "A platform that allows citizens to participate in urban planning decisions through crowdsourced inputs and feedback.",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-10"),
    isPublic: true,
    userId: "67d78d872e2ed2dc35e42b23",
    userBuyMeACoffeeUrl: "https://buymeacoffee.com/urbanplanning",
    industry: ["government", "technology", "construction"],
    tags: ["urban planning", "civic engagement", "smart cities", "crowdsourcing", "community"],
    upVotes: 78,
    downVotes: 22,
    problemStatement: "Urban planning often lacks meaningful citizen input, leading to developments that don't serve community needs.",
    relatedUrls: ["https://example.com/participatory-planning", "https://example.com/smart-cities"],
    stage: "idea",
    risks: ["Government adoption", "Representative participation", "Implementation challenges"],
    businessModel: BusinessModel.saas,
    uniqueValue: "Crowdsourced urban planning platform that allows citizens to participate in urban planning decisions through crowdsourced inputs and feedback.",
  },
  {
    _id: "65f8ae4c2e5df1e0bd8b3a56",
    title: "Microplastic Filtration System for Washing Machines",
    description: "An attachment for washing machines that filters microplastics from wastewater before it enters the water system.",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-03-15"),
    isPublic: true,
    userId: "67d78d872e2ed2dc35e42b23",
    userBuyMeACoffeeUrl: "https://buymeacoffee.com/microplasticfilter",
    industry: ["environmental", "manufacturing", "technology"],
    tags: ["microplastics", "water pollution", "sustainability", "cleantech", "home appliances"],
    upVotes: 103,
    downVotes: 7,
    problemStatement: "Washing synthetic clothing releases microplastics into waterways, contributing to environmental pollution.",
    relatedUrls: ["https://example.com/microplastic-research", "https://example.com/water-filtration"],
    stage: "validation",
    risks: ["Filter efficiency", "Installation complexity", "Cost barriers"],
    businessModel: BusinessModel.physicalProduct,
    uniqueValue: "Microplastic filtration system for washing machines that filters microplastics from wastewater before it enters the water system.",
  },
  {
    _id: "65f8ae4c2e5df1e0bd8b3a57",
    title: "AI-Powered Elderly Care Companion",
    description: "A smart companion device that provides assistance, medication reminders, health monitoring, and companionship for elderly individuals.",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-03-12"),
    isPublic: true,
    userId: "67d78d872e2ed2dc35e42b23",
    userBuyMeACoffeeUrl: "https://buymeacoffee.com/elderlycompanion",
    industry: ["healthcare", "artificialIntelligence", "technology"],
    tags: ["elderly care", "ai", "health monitoring", "companionship", "aging in place"],
    upVotes: 116,
    downVotes: 9,
    problemStatement: "Elderly individuals often face isolation, forgetting medications, and delayed response to health issues.",
    relatedUrls: ["https://example.com/elderly-care-innovation", "https://example.com/ai-health-companions"],
    stage: "mvp",
    risks: ["User adoption", "Technical reliability", "Healthcare integration"],
    businessModel: BusinessModel.hardwarePlusSoftware,
    uniqueValue: "AI-powered elderly care companion that provides assistance, medication reminders, health monitoring, and companionship for elderly individuals.",
  },
  {
    _id: "65f8ae4c2e5df1e0bd8b3a58",
    title: "Blockchain-Based Intellectual Property Registry",
    description: "A decentralized platform for creators to register and protect their intellectual property using blockchain technology.",
    createdAt: new Date("2024-02-25"),
    updatedAt: new Date("2024-03-08"),
    isPublic: true,
    userId: "67d78d872e2ed2dc35e42b23",
    userBuyMeACoffeeUrl: "https://buymeacoffee.com/ipregistry",
    industry: ["blockchain", "legalServices", "technology"],
    tags: ["intellectual property", "blockchain", "copyright", "creators", "digital rights"],
    upVotes: 89,
    downVotes: 18,
    problemStatement: "Creators struggle to protect their intellectual property in the digital age without costly legal services.",
    relatedUrls: ["https://example.com/blockchain-ip", "https://example.com/digital-rights"],
    stage: "prototype",
    risks: ["Regulatory recognition", "Blockchain scalability", "User education"],
    businessModel: BusinessModel.blockchainBased,
    uniqueValue: "Decentralized platform for creators to register and protect their intellectual property using blockchain technology.",
  },
  {
    _id: "65f8ae4c2e5df1e0bd8b3a59",
    title: "Augmented Reality Home Renovation Tool",
    description: "An AR app that allows homeowners to visualize renovation projects in their actual space before beginning work.",
    createdAt: new Date("2024-03-05"),
    updatedAt: new Date("2024-03-15"),
    isPublic: true,
    userId: "67d78d872e2ed2dc35e42b23",
    userBuyMeACoffeeUrl: "https://buymeacoffee.com/arrenovation",
    industry: ["realEstate", "technology", "construction"],
    tags: ["augmented reality", "home renovation", "interior design", "visualization", "diy"],
    upVotes: 72,
    downVotes: 14,
    problemStatement: "Homeowners struggle to visualize renovation outcomes, leading to costly revisions and disappointment.",
    relatedUrls: ["https://example.com/ar-design", "https://example.com/home-renovation-tech"],
    stage: "validation",
    risks: ["AR accuracy", "User experience", "Hardware limitations"],
    businessModel: BusinessModel.freemium,
    uniqueValue: "Augmented reality home renovation tool that allows homeowners to visualize renovation projects in their actual space before beginning work.",
  },
  {
    _id: "65f8ae4c2e5df1e0bd8b3a60",
    title: "Decentralized Renewable Energy Marketplace",
    description: "A platform that connects small-scale renewable energy producers with consumers, enabling peer-to-peer energy trading.",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-03-01"),
    isPublic: true,
    userId: "67d78d872e2ed2dc35e42b23",
    userBuyMeACoffeeUrl: "https://buymeacoffee.com/p2penergy",
    industry: ["energy", "renewableEnergy", "blockchain"],
    tags: ["renewable energy", "p2p", "energy trading", "sustainability", "decentralization"],
    upVotes: 98,
    downVotes: 21,
    problemStatement: "Small-scale renewable energy producers lack efficient ways to sell excess energy directly to consumers.",
    relatedUrls: ["https://example.com/p2p-energy", "https://example.com/renewable-marketplace"],
    stage: "launched",
    risks: ["Regulatory hurdles", "Grid integration", "Market adoption"],
    businessModel: BusinessModel.marketplace,
    uniqueValue: "Decentralized renewable energy marketplace that connects small-scale renewable energy producers with consumers, enabling peer-to-peer energy trading.",
  }
];